### ISSUE TITLE
Calling startActivity()

### ISSUE THREAD

**Issue by TechNerdsUzi** [dpa99c/react-native-launch-navigator#1]
i have an error while lunch google maps
Error: Calling startActivity() from outside of an activity context requires the FLAG_ACTIVITY_NEW_TASK flag. is this really what you want ?

can you tell me how to fix this ?

**Comment by dpa99c** [comment]
I haven't encountered this problem in the [example test project](https://github.com/dpa99c/react-native-launch-navigator-example) - have you tried building and running it?

And are you by any chance using [react-native-navigation](https://github.com/wix/react-native-navigation) in your project? Since React Native is mono-activity by default, `react-native-navigation` is the most common way that multiple activities are introduced into React Native apps.

[This SO answer](https://stackoverflow.com/a/3918838/777265) indicates the quickest fix would be to set the `FLAG_ACTIVITY_NEW_TASK` flag on the intent, but I fear this would interfere with the history stack of  `react-native-navigation`. 

Currently this module [uses the `getReactApplicationContext()` method of the `ReactContextBaseJavaModule` parent class](https://github.com/dpa99c/react-native-launch-navigator/blob/master/android/src/main/java/uk/co/workingedge/RNLaunchNavigator/RNLaunchNavigatorModule.java#L35) to pass as context to the `LaunchNavigator` class for use in launch intents.

However, I will investigate if it's possible to obtain a reference to the current activity via the parent class, as I think passing the Activity context instead of the Application context would resolve this issue.

**Comment by dpa99c** [comment]
The above commit is published in v1.0.1
Please let me know if that doesn't resolve your issue.
