### ISSUE TITLE
Feature Request: Multiple locations entry required.

### ISSUE THREAD

**Issue by vivekshah-zymr** [dpa99c/react-native-launch-navigator#7]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

**Current behaviour:**
I want to open a map with multiple locations, like source, destination 1, destination 2, destination 3 and the final destination. But right now I am not able to open map with only source and destination.

**Expected behaviour:**
There should be a function that takes multiple locations to display on a map.

Please review this and let me know.

**Comment by dpa99c** [comment]
This has been asked before (https://github.com/dpa99c/phonegap-launch-navigator/issues/98) and the answer is that it's not possible because it requires the navigation apps to support specifying multiple locations (waypoints) in their URL schemes.

Google Maps used to be the only app supported by this plugin which a supported multiple locations in its URL scheme, but that [seems to no longer work](https://github.com/dpa99c/phonegap-launch-navigator/issues/98#issuecomment-280783506), although I haven't tested it myself again recently.
